---

# ansible_connection: httpapi
ansible_connection: network_cli
#ansible_connection: ssh

ansible_hhtpapi_use_ssl: yes
ansible_httpapi_validate_certs: no 
ansible_network_os: nxos
ansible_user: admin
#ansible_httpapi_pass: 
#ansible_ssh_common_args: -o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa