---
# vars file for leaf

features:
  - { feature: bgp }
  - { feature: interface-vlan }
  - { feature: ospf }
  - { feature: pim }
  - { feature: vnseg_vlan }    


ospf_process_id: UNDERLAY

ospf_area: 0

asn: 65001

address_families:
  - { afi: l2vpn, safi: evpn }
  - { afi: ipv4, safi: unicast } 

bgp_neighbors:
  - { remote_as: 65001, neighbor: 10.10.10.11, update_source: Loopback0 }

rp_address: 1.1.1.1

vlans_l2vni:
  - { vlan_id: 10, vni_id: 10010, addr: 10.0.10.1, mask: 24, mcast_grp: 239.0.0.10, vrf: Tenant-1 }
  - { vlan_id: 20, vni_id: 10020, addr: 10.0.20.1, mask: 24, mcast_grp: 239.0.0.20, vrf: Tenant-1 }
  - { vlan_id: 30, vni_id: 10030, addr: 10.0.30.1, mask: 24, mcast_grp: 239.0.0.30, vrf: Tenant-1 } 
  - { vlan_id: 40, vni_id: 10040, addr: 10.0.40.1, mask: 24, mcast_grp: 239.0.0.40, vrf: Tenant-1 }
  - { vlan_id: 50, vni_id: 10050, addr: 10.0.50.1, mask: 24, mcast_grp: 239.0.0.50, vrf: Tenant-1 }

vlans_l3vni:
  - { vlan_id: 10, vni_id: 10000, vrf: Tenant-1 }

vrfs:
  - { vrf: Tenant-1, vni_id: 10000, afi: ipv4, safi: unicast }
