---
#  variables for SW-02 N0k

host_name: "SW-02-ANSIBLE"

router_id: 10.10.10.22

loopbacks:
  - { interface: loopback0, addr: 10.10.10.22, mask: 32 }
  - { interface: loopback1, addr: 2.2.2.2, mask: 32 }

# links to spine

interfaces:
  - { interface: ethernet1/1, addr: 10.1.2.2, mask: 30, description: "p2p-CORE-01" } 
  - { interface: ethernet1/2, addr: 10.2.2.2, mask: 30, description: "p2p-CORE-02" } 