---
#  variables for SW-01 N9k

host_name: "SW-01-ANSIBLE"

router_id: 10.10.10.21

loopbacks:
  - { interface: loopback0, addr: 10.10.10.21, mask: 32 }
  - { interface: loopback1, addr: 2.2.2.1, mask: 32 }

# links to spine

interfaces:
  - { interface: ethernet1/1, addr: 10.1.1.2, mask: 30, description: "p2p-CORE-01" } 
  - { interface: ethernet1/2, addr: 10.2.1.2, mask: 30, description: "p2p-CORE-02" } 