---
#  variables for Core-01 N9k

host_name: "CORE-01-ANSIBLE"

router_id: 10.10.10.10

loopbacks:
  - { interface: loopback0, addr: 10.10.10.10, mask: 32 }
  - { interface: loopback1, addr: 1.1.1.1, mask: 32 }

# Core-01 down links to spine
interfaces:
  - { interface: ethernet1/3, addr: 10.1.1.1, mask: 30, description: "p2p-SW-01" } 
  - { interface: ethernet1/4, addr: 10.1.2.1, mask: 30, description: "p2p-SW-02" } 
  - { interface: ethernet1/5, addr: 10.1.3.1, mask: 30, description: "p2p-SW-03" } 